[package]
name = "yuto51942-servant"
version = "0.1.2"
edition = "2021"
authors = ["Yuto Watanabe <yuto.w51942@gmail.com>"]
license = "MIT"
repository = "https://github.com/yuto51942/servant"
description = "Utilities cli."
readme = "README.md"
exclude = [
    ".github/*",
]
include = [
    "**/*.rs",
    "Cargo.toml",
]
[[bin]]
name = "sv"
path = "src/main.rs"

[dependencies]
structopt = "0.3.23"
termion = "1.1.1"
