[package]
name = "sv"
version = "0.1.0"
edition = "2021"
authors = ["Yuto Watanabe <yuto.w51942@gmail.com>"]
license = "MIT"
repository = "https://github.com/yuto51942/servant"
readme = "README.md"
exclude = [
    ".github/*",
]
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
structopt = "0.3.23"
